"""Generate ERROR_SAMPLES.md: real error output for typical mistakes.

Run:  python3 examples/error_samples.py > ERROR_SAMPLES.md
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from cliparse import ParseError, Parser  # noqa: E402


def build_parser():
    p = Parser(prog="deploy", description="deploy a service",
               exit_on_error=False)
    p.add_option("--verbose", "-v", help="verbose logging")
    p.add_option("--env", "-e", takes_value=True, metavar="NAME",
                 default="staging", help="target environment")
    p.add_option("--replicas", "-r", takes_value=True, type=int, default=1,
                 metavar="N", help="replica count")
    p.add_positional("service", help="service to deploy")
    run = p.add_subcommand("rollback", help="roll back a deploy")
    run.add_option("--steps", "-s", takes_value=True, type=int, default=1)
    return p


CASES = [
    ("Unknown long option (with suggestion)", ["--verbse", "web"]),
    ("Unknown short option", ["-z", "web"]),
    ("Missing required value (end of argv)", ["web", "--env"]),
    ("Missing value: next token looks like an option",
     ["--env", "--verbose", "web"]),
    ("Invalid value type", ["--replicas", "two", "web"]),
    ("Boolean flag given a value", ["--verbose=yes", "web"]),
    ("Missing required positional argument", ["--env", "prod"]),
    ("Unknown option inside a subcommand", ["rollback", "--step", "2"]),
]


def main():
    print("# Error message samples")
    print()
    print("Generated by `python3 examples/error_samples.py`.")
    print("Every error prints usage + `error: ...` to stderr and uses")
    print("exit code 2 (returned via `ParseError.exit_code` when")
    print("`exit_on_error=False`).")
    for title, argv in CASES:
        parser = build_parser()
        print()
        print("## %s" % title)
        print()
        print("    $ deploy %s" % " ".join(argv))
        print()
        print("```")
        try:
            parser.parse(argv)
            print("(no error)")
        except ParseError as err:
            print(err.format())
        print("```")
    print()
    print("## Missing subcommand (subcommand_required=True)")
    print()
    print("    $ tool")
    print()
    print("```")
    tool = Parser(prog="tool", exit_on_error=False, subcommand_required=True)
    tool.add_subcommand("run", help="run it")
    tool.add_subcommand("stop", help="stop it")
    try:
        tool.parse([])
    except ParseError as err:
        print(err.format())
    print("```")


if __name__ == "__main__":
    main()
